# Generated by Django 2.2 on 2020-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Cuisine',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
