# Generated by Django 2.2 on 2020-08-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200822_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Cuisine',
        ),
    ]
